CREATE TABLE t_user (
id BIGSERIAL PRIMARY KEY,
username VARCHAR(255),
email VARCHAR(255) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
role VARCHAR(50)
);

CREATE TABLE t_category (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
user_id BIGINT NOT NULL,
FOREIGN KEY (user_id) REFERENCES t_user(id) ON DELETE CASCADE
);

CREATE TABLE t_expense (
id BIGSERIAL PRIMARY KEY,
amount DOUBLE PRECISION NOT NULL,
description VARCHAR(255),
DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
category_id BIGINT NOT NULL,
user_id BIGINT NOT NULL,
FOREIGN KEY (category_id) REFERENCES t_category(id) ON DELETE CASCADE,
FOREIGN KEY (user_id) REFERENCES t_user(id) ON DELETE CASCADE
);